server:
  port: 9091
  
spring:
  application:
    name: VRINITY-eureka-server
    
#Config Server      
  cloud:
    config:
      uri: http://localhost:8888 
      name: VRINITY-config-server
      
#Eureka Standalone Server       
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
      